name: 'Comment rotation action'
description: 'Adds a comment to the PR and removes previously added comment if it already ran on the PR.'
branding:
  icon: activity
  color: orange
inputs:
  comment:
    description:
      'Comment to post'
    required: true
  prNumber:
    description:
      'PR number to post the comment on'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token to post/remove comments. The workflow must have the permissions: `issues: write` and `pull-requests: write`.'
    required: true
  GITHUB_REPOSITORY:
    description: 'The repository where the PR is located. e.g. `microsoftgraph/kiota`'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    COMMENT: ${{inputs.comment}}
    PR_NUMBER: ${{inputs.prNumber}}
    GH_TOKEN: ${{inputs.GITHUB_TOKEN}}
    GITHUB_REPOSITORY: ${{inputs.GITHUB_REPOSITORY}}