name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        dockerfile: [ 'export', 'tool', 'comment' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker ${{ matrix.dockerfile }} image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./${{ matrix.dockerfile }}
