name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        dockerfile: [ 'export', 'tool', 'comment' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker ${{ matrix.dockerfile }} image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./${{ matrix.dockerfile }}

  # The check-typescript-version-matrix returns success if all matrix jobs in build are successful; otherwise, it returns a failure.
  # Use this as a PR status check for GitHub Policy Service instead of individual matrix entry checks.
  check-docker-build-matrix:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - name: All build matrix options are successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: One or more build matrix options failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1