name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker export
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./export
    - name: Build the Docker tool
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./tool
    - name: Build the Docker comment
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./comment
